# Generated by Django 3.1.12 on 2021-08-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20201110_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='latitude',
            field=models.FloatField(default=0, max_length=140),
        ),
        migrations.AddField(
            model_name='post',
            name='longitude',
            field=models.FloatField(default=0, max_length=140),
        ),
    ]
