# Generated by Django 3.1.12 on 2021-08-30 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
