# Generated by Django 3.1.12 on 2021-10-19 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20210831_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mexico_states',
            field=models.TextField(default=0, max_length=1000),
        ),
    ]
