# Generated by Django 3.1.12 on 2021-12-08 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_post_mexico_states'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='mexico_states',
        ),
    ]
