# Generated by Django 3.1.12 on 2021-12-09 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_post_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='estado',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
